# -*- coding: utf-8 -*-
"""waether_website.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KcWeXkEDHF-TmcjdcjE9oBDmgtkLvTOB
"""

import joblib
import pandas as pd
import streamlit as st

# 1. ضبط إعدادات الصفحة في البداية دائماً
st.set_page_config(page_title="temperature predictor", page_icon="🌡")

st.title("توقع درجة الحرارة 🌏")
st.write("ادخل قيم الطقس وهيتوقعلك درجة الحرارة")

st.divider()


# 2. تحميل الموديل المحفوظ
@st.cache_resource
def load_model():
  try:
    return joblib.load("weather_model_DT.pkl")
  except FileNotFoundError:
    st.error("❌ لم يتم العثور على ملف الموديل 'weather_model_DT.pkl'.")
    return None


model = load_model()

# 3. واجهة مدخلات المستخدم
col1, col2 = st.columns(2)

with col1:
  precip_type = st.selectbox("🌧 اختر نوع الهطول", options=["rain", "snow"])
  precip_type_val = 0 if precip_type == "rain" else 1

  # تعديل النص للتوضيح (Apparent Temperature)
  apparent_temp = st.number_input("Apparent Temperature (C)", value=20.0)

  humidity = st.slider("الرطوبة", min_value=0.0, max_value=1.0, value=0.5)

  wind_speed = st.number_input("سرعة الرياح (km/h)", value=10.0)

  wind_beering = st.slider(
      "Wind Bearing (degrees)", min_value=0, max_value=360, value=180
  )

with col2:
  visibility = st.number_input("مستوى الرؤية (km)", min_value=0.0, value=10.0)

  loud_cover = st.number_input("مستوى السحب (Loud Cover)", value=0.0)

  pressure = st.number_input("الضغط الجوي (millibars)", value=1013.0)

  # تصحيح الشهور لتبدأ من 1 إلى 12
  month = st.selectbox("اختر الشهر", options=list(range(1, 13)), index=0)

  hour = st.selectbox("الساعة كام", options=list(range(0, 24)), index=12)

st.divider()

# 4. زر التوقع وإعداد البيانات
if st.button("توقع درجة الحرارة 🔎", use_container_width=True):
  if model is None:
    st.error("تعذر إجراء التوقع لأن ملف الموديل غير موجود.")
  else:
    # تجميع الـ Features بأسماء تطابق تماماً ما تم تدريب الموديل عليه
    features = {
        "Precip Type": precip_type_val,
        "Apparent Temperature (C)": apparent_temp,  # التعديل هنا
        "Humidity": humidity,
        "Wind Speed (km/h)": wind_speed,
        "Wind Bearing (degrees)": wind_beering,
        "Visibility (km)": visibility,
        "Loud Cover": loud_cover,
        "Pressure (millibars)": pressure,
        "month": month,  # التعديل هنا (m سمول)
        "Hour": hour,
    }

    # الترتيب الصحيح للأعمدة كما في x_train
    column_order = [
        "Precip Type",
        "Apparent Temperature (C)",
        "Humidity",
        "Wind Speed (km/h)",
        "Wind Bearing (degrees)",
        "Visibility (km)",
        "Loud Cover",
        "Pressure (millibars)",
        "month",
        "Hour",
    ]

    # إنشاء DataFrame بدون أقواس إضافية حول column_order
    input_df = pd.DataFrame([features], columns=column_order)

    # حساب التوقع
    results = model.predict(input_df)[0]

    # عرض النتيجة
    st.success(f"### درجة الحرارة المتوقعة هي: {results:.2f} °C")

    with st.expander("عرض البيانات المدخلة للموديل"):
      st.dataframe(input_df)