# -*- coding: utf-8 -*-
"""waether_website.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KcWeXkEDHF-TmcjdcjE9oBDmgtkLvTOB
"""

import sys
!{sys.executable} -m pip install -q streamlit

import streamlit as st

"""# page title"""

st.set_page_config(page_title="temperature predictor",page_icon="🌡")

st.title("توقع درجة الحرارة 🌏")
st.write("ادخل قيم الطقس و هيتوقعلك درجة الحرارة ")

st.divider()

import joblib
def load_model():
  return joblib.load("weather_model_DT.pkl")
model=load_model()

col1,col2=st.columns(2)

with col1:
  #اول معلومة
  precip_type=st.selectbox("🌧اختر نوع الهطول",options=['rain','snow'])
  precip_type_val=0 if precip_type=="rain" else 1
  #تاني معلومة
  apparent_temp=st.number_input("apparent tempareture C",value=20.0)
  #تالت معلومة
  humidity=st.slider("الرطوبة",min_value=0.0,max_value=1.0,value=0.5)
  #رابع معلومة
  wind_speed=st.number_input("سرعة الرياح",value=10)
  #خامس معلومة
  wind_beering=st.slider("wind beering",min_value=0,max_value=360,value=180)

with col2:
  visibility=st.number_input("مستوي الرؤية ",min_value=0.0,value=10.0)
  loud_cover=st.number_input("مستوي السحب",value=0.0)
  pressure=st.number_input("الضغط الجوي",value=1013.0)
  month=st.selectbox("اختر الشهر",options=list(range(0,13)),index=0)
  hour=st.selectbox("الساعة كام",options=list(range(0,24)),index=0)
st.divider()

import pandas as pd
if st.button("توقع درجة الحرارة🔎 "):
  #فهمته معني كل داتا تقابلها ايه في الجداول
  features={
      "Precip Type":precip_type_val,
      "Temperature (C)":apparent_temp,
      "Humidity":humidity,
      "Wind Speed (km/h)":wind_speed,
      "Wind Bearing (degrees)":wind_beering,
      "Visibility (km)":visibility,
      "Loud Cover":loud_cover,
      "Pressure (millibars)":pressure,
      "Month":month,
      "Hour":hour
  }
  #رتبنا العواميد
  column_order=["Precip Type","Temperature (C)","Humidity","Wind Speed (km/h)","Wind Bearing (degrees)","Visibility (km)","Loud Cover","Pressure (millibars)","Month","Hour"]
  #حولناها بدل list الي جدول
  input_df=pd.DataFrame([features][column_order])
  #دخلناها للموديل
  results=model.predict(input_df)[0]
  #عرضنا النواتج
  st.success(f"درجة الحرارة هي {results}")